apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scimitar-pv-claim
  namespace: kube-system
spec:
  storageClassName: scimitar-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi