apiVersion: ENC[AES256_GCM,data:I6g=,iv:72uvHACYOeT2MWkChrhMYizgfgCx7a17AcBbItPqr/Y=,tag:ytV7L4YbB+uj/qfTgeqOKA==,type:str]
kind: ENC[AES256_GCM,data:XDDOJUuG,iv:QJMGpGfdA7efLSn6yQTbNLATf/TCRZKIM8ATzJQyfzA=,tag:F7gXcUqmMp6BAq9Mqar1WA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NM/IwMXjn+af0ahs3PbG,iv:/27QMJQwF0IoMVONvy4cXUSCX2DaftdUYmil5+vibWM=,tag:tfJtJAkeRTaDO6lZ+8xC1g==,type:str]
    namespace: ENC[AES256_GCM,data:J+tZvGMh6+Y=,iv:O5em8HzNqy+ghAE0pE0Yia9SzAJ+NSk/+2Qre8NOoG0=,tag:k3ydx7zOTUTu2ga+C0Bcng==,type:str]
data:
    admin-password: ENC[AES256_GCM,data:4Ruc4zpcBfY=,iv:mBw2lA5EIXTz28pbymKEaCbKQ7FDjtjaNnmVsi+V4Jc=,tag:XPehlJGpVTLS9Vp3U+D94w==,type:str]
sops:
    age:
        - recipient: age15xkpdtjhalua0x9lg8r5g4kaue2hjphq5r8mpsun7n6445ks84psqhz9ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeDhWTzYyRHI1U2oxOXdP
            TUVIZ0FldTFpSmxoSStKVlFZa3NVRGI3RVNFCmxqUHFEZ3orWnNHQ1Jpd3pXNm5y
            SXpDZkIrZEpPY0xCV0s5OVVVK2hha0kKLS0tIGdkMGx3di95YW41amFFbHBaK2hO
            UERpTXpPNVNUVGJPNElDejAweVJFcVUKS6NMvo0v08XtY5nZi9aCPKB0qhGyYEf2
            CRYD+mV5ukAqiQx7GDi8V/XJKdksVJ9M2lXrSqapfJLhm+zXq1mCQw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jyklxpn59trjjkd5tw3ryv2wwqq4matk7amhtswdfhvces88cprs48v2hw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeWVuTXBCT0hqeGM5WDIw
            cUtBT3FoVzNhYVpnSGRtVy80d0c1dDM3QkhvCmRRSDlWSFEvQk0xUHhxdUZYTzJh
            elFmWk4yc2N6Mi90UjNLUlVRdnFHNUkKLS0tIHBSWm42REUrU1ZSSElnbjgwbXdU
            N2VxMk1oRVVDYmdFUTdzQzV1SG5CNlEKE5wubt9c4+DXvxHkZPf/jzAriHnakuWe
            sKowMoWtQnUB2oCrwJmoXnU90Bx0UHwUVc+FhBkG9Cjif79FFSEa7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T11:01:42Z"
    mac: ENC[AES256_GCM,data:kPyYltatqjKaaNBPfS8DrJy7vjneNk8yZHqjqECnPaD9ikOEgJjVjWa0LrqWyIdhYxfSTfDYH5GDKVvgQPcO/IRXxAxFJ1MFfAfBU9WfLIF6It/0J6TmO3VH3Oq3ot56YofZ7bdWOlu7Rc2+4ihYTPa7Sfb45eq3bnVhOmeplqg=,iv:KPXLrsaTIsfCcBoNAScZpLs0vErTHGWHrauSqZnEzXc=,tag:bxyIo6+cGw5G4Mrz40Ux8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
