apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: exercises
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-db
          image: docker.io/postgres:18.1
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: exercise-config
                  key: db_host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: scimitar-secret
                  key: db_username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: scimitar-secret
                  key: db_password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: db_name
                  name: exercise-config
          command:
            - /bin/sh
            - -c
            - |
              until psql -h "$DB_HOST" -U "$DB_USER" -d "$DB_NAME" -c 'SELECT 1 FROM pingpong' >/dev/null 2>&1; do
                echo "Waiting for database..."
                sleep 2
              done
              echo "Database is ready!"
      containers:
        - name: scimitar-backend
          image: matsubokkuri/scimitar-backend:2.7
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: exercise-config
                  key: db_host
      restartPolicy: Always
  # psql -h postgres-svc.postgres -U scimntair -d scimitar -c "SELECT 1 from pingpong;"