apiVersion: ENC[AES256_GCM,data:pBk=,iv:C2PZhuqKbgnwxojtZotUPx+ccw8vzCsWrXTdcBwJXpk=,tag:cuZlUpLGmelSwAlTNKc65g==,type:str]
kind: ENC[AES256_GCM,data:eF3tXDCa,iv:F+s/y1gyRHIAVDinF8Lt9KKbK2Z0iqvMprQ0YQuBP+4=,tag:6UYxLP6dHbNdzeNAnYc+Iw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:v2envaUm07G+Qh55hzDg,iv:18xGJ+9vPhbdNLUPCkylOTRXObGdba/LhtAeIsMNvyE=,tag:6Cx/YjIH+7jzARYAz1AdKw==,type:str]
type: ENC[AES256_GCM,data:/zEHRBBvmj7IIOBi+8I3Cp5qXb/Alogc,iv:4e6d2l9LYZUTkGMdNf7AqbqLiKNDyBWkMz/8UpBM4YA=,tag:Y7O5oVyxZEq6MxFMhv1O7g==,type:str]
stringData:
    username: ENC[AES256_GCM,data:xJF8bor0qywbrfrn,iv:9eEjbkC8fbZkstds79Y4OwL/cm78mewz4+Sz+5IRaqI=,tag:bGejjum6ZO6s5zIGbXI4Vw==,type:str]
    password: ENC[AES256_GCM,data:FPcOes3aDBNSqR3aU29XxQ==,iv:A1YjF9Tp2Cl+0a9U5UWlkIC1ziHdcsFFY4DIDAvsOco=,tag:a7c37kPXr2Xmu6dJkS2G4Q==,type:str]
sops:
    age:
        - recipient: age15xkpdtjhalua0x9lg8r5g4kaue2hjphq5r8mpsun7n6445ks84psqhz9ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVm8zaC9iSm82cFExN2Nj
            TkxmZC9OcGdVQU9uOHhCbjVaNEhLb2pUR2s0ClRDalEzNDAzaW82TFFPUSs2NFZ0
            WkQ3OGNyaVN1NkFNOFBSSmZyV0dEalkKLS0tIDlTUU9sYi9zRXBNUGJtUEpNVkNP
            Yzl0NG40ZUhiKzFjNEI3K0VUSTdKa2sKsEJI0pLaKuCyrPQMoTR5V7s8UpRW0YRb
            KH2ULK+qTbefTavXhgMtQd8AGGNGFyKYhZ546C1kopDBjngndxl3MA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jyklxpn59trjjkd5tw3ryv2wwqq4matk7amhtswdfhvces88cprs48v2hw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVWNpcFFFTllzR3BvQTVZ
            WEMxeHVjRllpTUl0SWFPaEFKejNyMmlwdTBZCklSNk1QSmxhZ1BkYXJIU0pOaTlK
            NmxVUnd1K0dqckhYczJ1aERmMURIUEUKLS0tIHVKSG0ySE9JUG1xZTl4L0J1dG5k
            MGkwU0NVaDNPTGdaaGN0MzVuOGQ5YUUKJEmxS8Y/QqNpypMQ2iQC1FTX9NRyxISa
            YnyCrKYc+4YJVQoeF4yUK5l0L07T60gMIVhWU6bJDWPLJG8JR25NOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T09:27:37Z"
    mac: ENC[AES256_GCM,data:XzCAulbDlD5J5l5ZIIIU6mF0zfwi8xUKDwDxc6qkX8ujQ8FBdgz2rLkVN1cZpF1qi80HQuXc1jGJ1QxDTinjGDYuuPnSo0EweIryaJe1Zft9tmn0mVARyLjh+FFc3G7AC9MJZRfa3X1xj7Bx5wsgxaKAXKVuKaqGkZaWfLpYm3s=,iv:X85R0ShyjvYLCAy3zBlT7wvOjkw/25rJ4VU2/3124kA=,tag:xL6FVMCPtlYTercoSoDP/Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
