apiVersion: ENC[AES256_GCM,data:D0U=,iv:o6VQSw+hrwoBRmnUHEnhAWJzs4engj827zKxq4tvZtM=,tag:mL+dxsOeaZK45LE2HaupwQ==,type:str]
kind: ENC[AES256_GCM,data:HMZLG/0H,iv:YSo8lYCY8qCqqnLzOPob/WW5VqpaGDjNsZYs9/jQgC4=,tag:AVpz4EEOURPJbievGRXzEg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tKxiwEEaK6HTDTycruo4,iv:qMJUniC628ydzMDBPIxKlsJhRqssgaDwRqQ4XEqhZL8=,tag:9S7Jb3gB2Cu1j7n+mRktow==,type:str]
    namespace: ENC[AES256_GCM,data:6gjYI7Z/TM7o,iv:6guUtsidVm/FA/3+QNeHtPhYUiy4bQcs2xJDJUuu0II=,tag:1SXm+Kxnh8QAoOBK5qlRjQ==,type:str]
type: ENC[AES256_GCM,data:+KX0fwmH,iv:eibFsAxhRRawYpunJrplptXPVh7NKv0NbI7XaCN6Wwk=,tag:zCrMX4qhf3fsYzibrelGpA==,type:str]
data:
    db_username: ENC[AES256_GCM,data:8Fi22DmkpFeiNFnE,iv:FS7UC5DEFEEPasQ2VELpUWivV9Q3glDcXin6bAU9NhE=,tag:gKWLu/SwSjVTc8VoHPUPLQ==,type:str]
    db_password: ENC[AES256_GCM,data:mrK93fP+nEFrmMQOtTd7QQ==,iv:5PtxO36vuxd93Rwu20E8spE6Kq1F/mAH50ppd4UfbvA=,tag:9E2MrHwLSPKY4A9ual4xUA==,type:str]
    dckr_token: ENC[AES256_GCM,data:mHvHpowcxAIHQPO+Kjj7ZXT4zTj7+XIK2FHPsDSTrpMjnLhw,iv:17+E+4aJ9Uel+SesqomQqjrv6gPw/KVg1YiQ7P05MU4=,tag:e+f4fwokpy00oGrTxN503A==,type:str]
sops:
    age:
        - recipient: age15xkpdtjhalua0x9lg8r5g4kaue2hjphq5r8mpsun7n6445ks84psqhz9ed
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZjV3c3FYSlZWc1RhdWV6
            SUVBWXFob2gxT2UyRGhIbHR4REQ4YXhCMEdNCllNbU92bjNXZlNEOXhhWnZLUDNi
            NmJGOGU0WmZnN3NFcGE4N1Q3Vm9NS1EKLS0tIHR3NGJMbGlMbUtiSlFSdE9UZHdh
            VHcvY0tEVE1tTjJUelo0U0pZQ2JWRlkKp7tv5Ic8kpsk+GCwaT66yNWVjUA6JMDZ
            61xGioeZmbeWSBEjff3om7oh19qXzbsRB2i2cvfzWPQqEaoyPwljZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jyklxpn59trjjkd5tw3ryv2wwqq4matk7amhtswdfhvces88cprs48v2hw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTStyRnd6NFJWdWlqaUoy
            ZWpiSHZUZVJEMVRlRWVxVzkxS2lOL3FTd2gwCkdzaHpLWVFJOUR4dkoyQkVIZ09U
            ekVHdTRyeENRQ2FValJQdGVkVUY2eDgKLS0tIEVLUzdBWGlMb2RKMER1YVpTTUlO
            VlpKYUU3QVpzOXYrd3VWcDRXT1dNRmsKxakTFVmPKHUujgBQURxQSQm19VBTbVC/
            F9vy2LvEwNWLNx6FQAYBtLgcU4Vf+jFa6ZZg3+AROdoWtMXuz4QpCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T14:27:25Z"
    mac: ENC[AES256_GCM,data:6uKRN5EwDNcJVitbaK18KP9Zi4b8E48TqqjOkb/Y5UJFKhEu7w3Bm/yWHSufQ0yzoSzTfmoC35TFWRsHylXyldTMTHuNu/2byrQ/u5UWotLVQhShCM/fqAS1NXpCdR+78WInd8emlXtzGq0gCeO1E/i5X+RflpS/1RDs7ibvyjs=,iv:yZWZdURARJkR7/mPRRRxr/g+sU5C0lmIx0l4+4NxWFw=,tag:S42iBTPMruQq1MdvNQodiw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
