apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/ns.yaml
  - manifests/pv.yaml
  - manifests/pvc.yaml
  - manifests/cm.yaml
  - manifests/secret.yaml
  - manifests/service.yaml
  - manifests/stateful.yaml